# Generated by Django 5.0.7 on 2026-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_email_remove_booking_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('auditorium', 'Аудиторія'), ('conference', 'Конференц-зал'), ('lab', 'Лабораторія'), ('other', 'Інше')], default='other', max_length=20),
        ),
    ]
