# Generated by Django 5.0.7 on 2026-02-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_room_description_remove_room_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
