# Generated by Django 5.0.7 on 2026-02-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_features_room_price_per_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
    ]
