# Generated by Django 5.0.7 on 2026-02-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_price_per_hour_room_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
