# Generated by Django 5.0.7 on 2026-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_room_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.TextField(blank=True, verbose_name='Особливості (проєктор, Wi-Fi, дошка тощо)'),
        ),
    ]
